unique_ids:
  assets:
    standard-page.html: K4WSZISACAODDSWRW72M2DD6HZ2LNMB4
    theme.css: ILNI32R4GSPNBSVNXNKLUYPG2OP4KD73
  forms:
    Form1: 4D5IJM43ZX5GEFSLV57B7JALUS65KGXM
  modules: {}
  scripts: {}
  server_modules: {}
