CREATE TABLE pokemon (
    region TEXT,
    id INTEGER PRIMARY KEY,
    name TEXT,
    type TEXT
);

INSERT INTO pokemon (region, id, name, type) VALUES
('Kanto', 1, 'Bulbasaur', 'Grass, Poison'),
('Kanto', 2, 'Ivysaur', 'Grass, Poison'),
('Kanto', 3, 'Venusaur', 'Grass, Poison'),
('Kanto', 4, 'Charmander', 'Fire'),
('Kanto', 5, 'Charmeleon', 'Fire'),
('Kanto', 6, 'Charizard', 'Fire, Flying'),
('Kanto', 7, 'Squirtle', 'Water'),
('Kanto', 8, 'Wartortle', 'Water'),
('Kanto', 9, 'Blastoise', 'Water'),
('Kanto', 10, 'Caterpie', 'Bug'),
('Kanto', 11, 'Metapod', 'Bug'),
('Kanto', 12, 'Butterfree', 'Bug, Flying'),
('Kanto', 13, 'Weedle', 'Bug, Poison'),
('Kanto', 14, 'Kakuna', 'Bug, Poison'),
('Kanto', 15, 'Beedrill', 'Bug, Poison'),
('Kanto', 16, 'Pidgey', 'Normal, Flying'),
('Kanto', 17, 'Pidgeotto', 'Normal, Flying'),
('Kanto', 18, 'Pidgeot', 'Normal, Flying'),
('Kanto', 19, 'Rattata', 'Normal'),
('Kanto', 20, 'Raticate', 'Normal'),
('Kanto', 21, 'Spearow', 'Normal, Flying'),
('Kanto', 22, 'Fearow', 'Normal, Flying'),
('Kanto', 23, 'Ekans', 'Poison'),
('Kanto', 24, 'Arbok', 'Poison'),
('Kanto', 25, 'Pikachu', 'Electric'),
('Kanto', 26, 'Raichu', 'Electric'),
('Kanto', 27, 'Sandshrew', 'Ground'),
('Kanto', 28, 'Sandslash', 'Ground'),
('Kanto', 29, 'Nidoran♀', 'Poison'),
('Kanto', 30, 'Nidorina', 'Poison'),
('Kanto', 31, 'Nidoqueen', 'Poison, Ground'),
('Kanto', 32, 'Nidoran♂', 'Poison'),
('Kanto', 33, 'Nidorino', 'Poison'),
('Kanto', 34, 'Nidoking', 'Poison, Ground'),
('Kanto', 35, 'Clefairy', 'Fairy'),
('Kanto', 36, 'Clefable', 'Fairy'),
('Kanto', 37, 'Vulpix', 'Fire'),
('Kanto', 38, 'Ninetales', 'Fire'),
('Kanto', 39, 'Jigglypuff', 'Normal, Fairy'),
('Kanto', 40, 'Wigglytuff', 'Normal, Fairy'),
('Kanto', 41, 'Zubat', 'Poison, Flying'),
('Kanto', 42, 'Golbat', 'Poison, Flying'),
('Kanto', 43, 'Oddish', 'Grass, Poison'),
('Kanto', 44, 'Gloom', 'Grass, Poison'),
('Kanto', 45, 'Vileplume', 'Grass, Poison'),
('Kanto', 46, 'Paras', 'Bug, Grass'),
('Kanto', 47, 'Parasect', 'Bug, Grass'),
('Kanto', 48, 'Venonat', 'Bug, Poison'),
('Kanto', 49, 'Venomoth', 'Bug, Poison'),
('Kanto', 50, 'Diglett', 'Ground'),
('Kanto', 51, 'Dugtrio', 'Ground'),
('Kanto', 52, 'Meowth', 'Normal'),
('Kanto', 53, 'Persian', 'Normal'),
('Kanto', 54, 'Psyduck', 'Water'),
('Kanto', 55, 'Golduck', 'Water'),
('Kanto', 56, 'Mankey', 'Fighting'),
('Kanto', 57, 'Primeape', 'Fighting'),
('Kanto', 58, 'Growlithe', 'Fire'),
('Kanto', 59, 'Arcanine', 'Fire'),
('Kanto', 60, 'Poliwag', 'Water'),
('Kanto', 61, 'Poliwhirl', 'Water'),
('Kanto', 62, 'Poliwrath', 'Water, Fighting'),
('Kanto', 63, 'Abra', 'Psychic'),
('Kanto', 64, 'Kadabra', 'Psychic'),
('Kanto', 65, 'Alakazam', 'Psychic'),
('Kanto', 66, 'Machop', 'Fighting'),
('Kanto', 67, 'Machoke', 'Fighting'),
('Kanto', 68, 'Machamp', 'Fighting'),
('Kanto', 69, 'Bellsprout', 'Grass, Poison'),
('Kanto', 70, 'Weepinbell', 'Grass, Poison'),
('Kanto', 71, 'Victreebel', 'Grass, Poison'),
('Kanto', 72, 'Tentacool', 'Water, Poison'),
('Kanto', 73, 'Tentacruel', 'Water, Poison'),
('Kanto', 74, 'Geodude', 'Rock, Ground'),
('Kanto', 75, 'Graveler', 'Rock, Ground'),
('Kanto', 76, 'Golem', 'Rock, Ground'),
('Kanto', 77, 'Ponyta', 'Fire'),
('Kanto', 78, 'Rapidash', 'Fire'),
('Kanto', 79, 'Slowpoke', 'Water, Psychic'),
('Kanto', 80, 'Slowbro', 'Water, Psychic'),
('Kanto', 81, 'Magnemite', 'Electric, Steel'),
('Kanto', 82, 'Magneton', 'Electric, Steel'),
('Kanto', 83, 'Farfetch\'d', 'Normal, Flying'),
('Kanto', 84, 'Doduo', 'Normal, Flying'),
('Kanto', 85, 'Dodrio', 'Normal, Flying'),
('Kanto', 86, 'Seel', 'Water'),
('Kanto', 87, 'Dewgong', 'Water, Ice'),
('Kanto', 88, 'Grimer', 'Poison'),
('Kanto', 89, 'Muk', 'Poison'),
('Kanto', 90, 'Shellder', 'Water'),
('Kanto', 91, 'Cloyster', 'Water, Ice'),
('Kanto', 92, 'Gastly', 'Ghost, Poison'),
('Kanto', 93, 'Haunter', 'Ghost, Poison'),
('Kanto', 94, 'Gengar', 'Ghost, Poison'),
('Kanto', 95, 'Onix', 'Rock, Ground'),
('Kanto', 96, 'Drowzee', 'Psychic'),
('Kanto', 97, 'Hypno', 'Psychic'),
('Kanto', 98, 'Krabby', 'Water'),
('Kanto', 99, 'Kingler', 'Water'),
('Kanto', 100, 'Voltorb', 'Electric'),
('Kanto', 101, 'Electrode', 'Electric'),
('Kanto', 102, 'Exeggcute', 'Grass, Psychic'),
('Kanto', 103, 'Exeggutor', 'Grass, Psychic'),
('Kanto', 104, 'Cubone', 'Ground'),
('Kanto', 105, 'Marowak', 'Ground'),
('Kanto', 106, 'Hitmonlee', 'Fighting'),
('Kanto', 107, 'Hitmonchan', 'Fighting'),
('Kanto', 108, 'Lickitung', 'Normal'),
('Kanto', 109, 'Koffing', 'Poison'),
('Kanto', 110, 'Weezing', 'Poison'),
('Kanto', 111, 'Rhyhorn', 'Ground, Rock'),
('Kanto', 112, 'Rhydon', 'Ground, Rock'),
('Kanto', 113, 'Chansey', 'Normal'),
('Kanto', 114, 'Tangela', 'Grass'),
('Kanto', 115, 'Kangaskhan', 'Normal'),
('Kanto', 116, 'Horsea', 'Water'),
('Kanto', 117, 'Seadra', 'Water'),
('Kanto', 118, 'Goldeen', 'Water'),
('Kanto', 119, 'Seaking', 'Water'),
('Kanto', 120, 'Staryu', 'Water'),
('Kanto', 121, 'Starmie', 'Water, Psychic'),
('Kanto', 122, 'Mr. Mime', 'Psychic, Fairy'),
('Kanto', 123, 'Scyther', 'Bug, Flying'),
('Kanto', 124, 'Jynx', 'Ice, Psychic'),
('Kanto', 125, 'Electabuzz', 'Electric'),
('Kanto', 126, 'Magmar', 'Fire'),
('Kanto', 127, 'Pinsir', 'Bug'),
('Kanto', 128, 'Tauros', 'Normal'),
('Kanto', 129, 'Magikarp', 'Water'),
('Kanto', 130, 'Gyarados', 'Water, Flying'),
('Kanto', 131, 'Lapras', 'Water, Ice'),
('Kanto', 132, 'Ditto', 'Normal'),
('Kanto', 133, 'Eevee', 'Normal'),
('Kanto', 134, 'Vaporeon', 'Water'),
('Kanto', 135, 'Jolteon', 'Electric'),
('Kanto', 136, 'Flareon', 'Fire'),
('Kanto', 137, 'Porygon', 'Normal'),
('Kanto', 138, 'Omanyte', 'Rock, Water'),
('Kanto', 139, 'Omastar', 'Rock, Water'),
('Kanto', 140, 'Kabuto', 'Rock, Water'),
('Kanto', 141, 'Kabutops', 'Rock, Water'),
('Kanto', 142, 'Aerodactyl', 'Rock, Flying'),
('Kanto', 143, 'Snorlax', 'Normal'),
('Kanto', 144, 'Articuno', 'Ice, Flying'),
('Kanto', 145, 'Zapdos', 'Electric, Flying'),
('Kanto', 146, 'Moltres', 'Fire, Flying'),
('Kanto', 147, 'Dratini', 'Dragon'),
('Kanto', 148, 'Dragonair', 'Dragon'),
('Kanto', 149, 'Dragonite', 'Dragon, Flying'),
('Kanto', 150, 'Mewtwo', 'Psychic'),
('Kanto', 151, 'Mew', 'Psychic');
